/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiagnosticStudioRouteImport } from './routes/diagnostic-studio'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IngestionRouteImport } from './routes/ingestion'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ExamGradeRouteImport } from './routes/exam.grade'
import { Route as ExamSetupRouteImport } from './routes/exam.setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticStudioRoute = DiagnosticStudioRouteImport.update({
  id: '/diagnostic-studio',
  path: '/diagnostic-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestionRoute = IngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamGradeRoute = ExamGradeRouteImport.update({
  id: '/exam/grade',
  path: '/exam/grade',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSetupRoute = ExamSetupRouteImport.update({
  id: '/exam/setup',
  path: '/exam/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic-studio': typeof DiagnosticStudioRoute
  '/help': typeof HelpRoute
  '/ingestion': typeof IngestionRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/exam/grade': typeof ExamGradeRoute
  '/exam/setup': typeof ExamSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic-studio': typeof DiagnosticStudioRoute
  '/help': typeof HelpRoute
  '/ingestion': typeof IngestionRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/exam/grade': typeof ExamGradeRoute
  '/exam/setup': typeof ExamSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic-studio': typeof DiagnosticStudioRoute
  '/help': typeof HelpRoute
  '/ingestion': typeof IngestionRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/exam/grade': typeof ExamGradeRoute
  '/exam/setup': typeof ExamSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/diagnostic-studio'
    | '/help'
    | '/ingestion'
    | '/login'
    | '/settings'
    | '/signup'
    | '/exam/grade'
    | '/exam/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/diagnostic-studio'
    | '/help'
    | '/ingestion'
    | '/login'
    | '/settings'
    | '/signup'
    | '/exam/grade'
    | '/exam/setup'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/diagnostic-studio'
    | '/help'
    | '/ingestion'
    | '/login'
    | '/settings'
    | '/signup'
    | '/exam/grade'
    | '/exam/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosticStudioRoute: typeof DiagnosticStudioRoute
  HelpRoute: typeof HelpRoute
  IngestionRoute: typeof IngestionRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  ExamGradeRoute: typeof ExamGradeRoute
  ExamSetupRoute: typeof ExamSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic-studio': {
      id: '/diagnostic-studio'
      path: '/diagnostic-studio'
      fullPath: '/diagnostic-studio'
      preLoaderRoute: typeof DiagnosticStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingestion': {
      id: '/ingestion'
      path: '/ingestion'
      fullPath: '/ingestion'
      preLoaderRoute: typeof IngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/grade': {
      id: '/exam/grade'
      path: '/exam/grade'
      fullPath: '/exam/grade'
      preLoaderRoute: typeof ExamGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/setup': {
      id: '/exam/setup'
      path: '/exam/setup'
      fullPath: '/exam/setup'
      preLoaderRoute: typeof ExamSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  DiagnosticStudioRoute: DiagnosticStudioRoute,
  HelpRoute: HelpRoute,
  IngestionRoute: IngestionRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  ExamGradeRoute: ExamGradeRoute,
  ExamSetupRoute: ExamSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
